export { BPA_DOMAINS, BPA_DOMAIN_ORIGINS, BPA_PANEL_SUBDOMAINS, getPanelOrigin, resolveDomainByHost } from "./domains";
export type { BpaDomain, BpaDomainKey } from "./domains";
export { getSeoConfig, getDomainSiteUrl } from "./config";
export type { SeoAppSurface, SeoConfig } from "./config";
export { buildPageMetadata } from "./metadata";
export type { PageMetadataInput } from "./metadata";
export { buildVerificationMetadata } from "./verification";
export { buildRobots } from "./robots";
export type { BuildRobotsInput, RobotsRuleInput } from "./robots";
export { buildSitemapEntries, buildSitemapUrl } from "./sitemap";
export type { SitemapEntryInput } from "./sitemap";
